language: node_js

os: linux
dist: focal
arch: amd64

node_js:
  - '14'

python:
  - '3.8'

install:
  - pip install deepcode

after_success:
  - snyk monitor

script:
  - yarn build
  - yarn test

branches:
  only:
    - main
    - develop
