language: node_js
os: linux
dist: focal
arch: amd64
env:
  matrix:
    - SH=zsh
  global:
    - secure: D32TTY+3p6IvvdQig5+pOGtQaz/h2PzYndOHQ3y6T7rkp6IicR8dDfeV1OOZ+fwxc5QAAuxAsQ8XQP5dlZ2ioKskG1hvxVRzJEx4Dm9GcG+mn9/Uj31d8RJPXzKtScUf1mZHFqaoTkyitz3ElFO2xQ++jkg2PFc6YUz2aFd6mYWmd2Lm2G28hAY5f/pVEoJ6m2PzA98Fv8bmlY7zD3YmPxdC/4+J6p72VCXsBR0YnJKr2Mi6uYLt/m0GJg9ma/qHBUwtWRTDVxa3ab63dPLalpb/YLAXWB8xV7xyhCy2gqylttYJ2o77+TYMpZsUYVUYQn3Lax0FU98bUdi6ScpAcxLqAsFYpJWnlvedWFJJa896Dgxv4NLVENa6jDh1ZPdYODxxr+UXFzIoG64ddeapJeQpWgI8bsf4Zghs1c5JOAcObfB8FyoYeQ/snKX+ibY7xMOrLbkFphxQ9o6seIZ4/x8LoPqHr5nKvW98JCM+U/hlo0VdMXZvPgnx9hKD5kz4o+FdNOCHbnssHkFL+Y1szQzQXyItkEgfqrzoFwjligPeb/CtpVwWRWWaLii4i3eOl415wnj43FMsi3Zahxxaf70NtQegmxgg6AtlzmPrlIDNhWp3XxBM5lp4VLB+cXcaiGn4gFTBEteDjbZRUBEiWVrFJjlmvyWIzYgOipjHGDw=
    - secure: qTKO9vHHbsvkqaGmZPiW08jDSU7ck8QQz1VXCwOTdsYjNq3G0euothNMTT1k8Eo7ZmocBWnZWxog1vFdVIhvrZun8xn8ETwpen6/8ybEeoBqAq6R3XIIKVTWBBV4FIaMot2BeK33rca/Mk8R67Le/F0PoZKeLnEG3qRIL40sWjLqGHHia3JAAseImnz0e4/7REiPY/YubmuRv1xxQhUo3Wxe+iOQ2cyKaEMsY0kgcgY8zTBzm06QxzLXAN2Sgb0LLOD/Tz9OYmJmkJU5A5HK3+fUckEZJn5bL0YVqErQpKTZmRRl3vO+tXn3e5rA0Ylq2SVrvvi0kKbSfEzNFaimBry9WYilScJ/tCJXxEEmybExFxdwRyECNkrmN03GwFOOZdQEHG6hCXTQnKtJXVTD1KVG5/TAsefS+PzxA4A8NVGdvxZIj9lK6YgKMTziWDpU1sMd193ul1YpFTYsdR7GQ+nMfJcce1PqPluE8Zs/xrk7Fmrrzi2nzn9v0otT7VAPUsdwBXoL97P1p1Ww0XJ76s21x3anEQqylKfWM7f9gbnuEidBBBqXV+/mboEHCFaZBANhpVpJ2TcU1Ajr2UteuApDOXCKSwlNYqxtUGiyWEL3qTsF6qsJ/Ld0uDzVWHDjASh98EuaIB2bS0/YJn3ZPdXTyBQTERgi8hT/75HpGh8=
    - secure: YWU4KivNkLOTjdTQaFvxPmWvu+QGtXxl+kg/1vf+4f75ZvmnOWi207uqkIQnzaQj3p32zgNVjlU+9L4XBFTasSfY+6qjDCP+wtwytr2vqGl20lzdqmcGaoTgRcUuwdE6G6hkh9m+9mjX3c1FmhD8AC4qFVnV7oaSVPtlFeoKfAN1D0DM7a3htK/soIAcxnwmqMr48VBFbL4ne7rumuRojW31zeQmR3Kp2n/g2riin5X9BmYwLeyMsoPmSXQXNC1edFGZhy3uoUo3wZB9izD4u0qtJQpaTVFT1vG8FW0pJtOVcmUHxwhODhPE+8TmpJNTXuXbaBnWiZj0gykD5Rn16ns5u62XMQ/S5UqA8/VWRamDQpH3NbkLyvLaZOXNIOoV6AM1x70HwPGyS7J3o8DRg9iCt95iQo+kl50D2cXXn1Unm+xuq8bCxLzCY0tJWTXJ24dFENTiqZUe1Y6wO8GHIJ52yIKsD1jj934OguEa+c0Tp4uped7lQmiSv/6EJWtBVgcviYp+RqoIIYzOo6gyINhL9KyZnlbXPbhUE5mwbK2RpvyY4Qf0MXIYWZip5Mqpp4G+ULh5rmD6iLhJaXc1XDXZE+CswAx1WJ106fSO/9gimGVQATSo4IRio1qi3NSyQh93ToCO5qh6VKRl9dtEIueccb3/X+MR+HzhZxw4BxM=
node_js:
  - '15'
before_install:
  - sudo apt-get install zsh
  - yarn set version latest
after_success:
  - snyk monitor
script:
  - yarn build
  - yarn test
branches:
  only:
    - main
    - develop
